## numpy

In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.7 MB 3.4 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.7 MB 3.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.7 MB 3.7 MB/s eta 0:00:03
   --------- ------------------------------ 3.1/12.7 MB 3.7 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.7 MB 3.8 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.7 MB 3.9 MB/s eta 0:00:02
   ------------------ --------------------- 6.0/12.7 MB 4.0 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.7 MB 4.1 MB/s eta 0:00:02
   ----------------------- ---------------- 7.6/12.7 MB 4.1 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.7 MB 4.1 MB/s eta 0:00:01
   ---------

In [2]:
import numpy as np 

In [ ]:
# 1D array
ar = np.array([1, 2, 3, 4, 5])
print(ar)

[1 2 3 4 5]


In [4]:
print(type(ar))

<class 'numpy.ndarray'>


In [5]:
# 2D array
ar2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(ar2)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
# 3D array
ar3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
print(ar3)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [ ]:
# N-dimentional array
ar4 = np.array([1, 2, 3, 4, 5], ndmin=5) # ndmin specifies the minimum number of dimensions
print(ar4)

[[[[[1 2 3 4 5]]]]]


In [ ]:
# Element wise operations
'''
+ - Add elements to arrays element-wise
- - Subtract elements from arrays element-wise
* - Multiply elements of arrays element-wise
/ - Divide elements of arrays element-wise

Note - number of elements in both arrays should be same for element-wise operations
'''

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a + b)  # Addition
print(a - b)  # Subtraction 
print(a * b)  # Multiplication
print(b / a)  # Division

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]


In [ ]:
# array creation methods
'''
1. np.zeros----> creates an array filled with zeros
2. np.ones-----> creates an array filled with ones
3. np.full ----> creates an array filled with a specified value
4. np.eye  ----> creates an identity matrix
5. np.arange --> creates an array with a range of values
6. np.random.rand --> creates an array with random float values
7. np.random.randint --> creates an array with random integer values
8. np.empty --> creates an empty array with a specified shape
9. np.copy --> creates a copy of an array
10. np.fromfunction --> creates an array by executing a function over each coordinate
11. np.fromiter --> creates an array from an iterable object
''' 

'\n1. np.zeros----> creates an array filled with zeros\n2. np.ones-----> creates an array filled with ones\n3. np.full ----> creates an array filled with a specified value\n4. np.eye  ----> creates an identity matrix\n5. np.arange --> creates an array with a range of values\n6. np.random.rand --> creates an array with random float values\n7. np.random.randint --> creates an array with random integer values\n8. np.ravel --> flattens a multi-dimensional array into a 1D array\n9. np.reshape --> reshapes an array to a specified shape\n10. np.empty --> creates an empty array with a specified shape\n11. np.copy --> creates a copy of an array\n12. np.fromfunction --> creates an array by executing a function over each coordinate\n13. np.fromiter --> creates an array from an iterable object\n'

In [12]:
np.zeros((2, 3))  # 2 rows and 3 columns filled with zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2, 3))  # 2 rows and 3 columns filled with ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.full((2, 3), 7)  # 2 rows and 3 columns filled with sevens

array([[7, 7, 7],
       [7, 7, 7]])

In [15]:
np.eye(3)  # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.arange(0, 10, 2)  # Array with values from 0 to 10 with a step of 2

array([0, 2, 4, 6, 8])

In [17]:
np.random.rand(2, 3)  # 2 rows and 3 columns filled with random float values

array([[0.41130303, 0.11551418, 0.0389182 ],
       [0.43912112, 0.87331375, 0.87457152]])

In [27]:
np.random.randint(0, 10)


1

In [28]:
np.random.randint(0, 10, (2, 3))  # 2 rows and 3 columns filled with random integers between 0 and 10

array([[2, 8, 4],
       [8, 7, 9]], dtype=int32)

In [19]:
np.empty((2, 3))  # Creates an empty array with shape 2x3

array([[0.41130303, 0.11551418, 0.0389182 ],
       [0.43912112, 0.87331375, 0.87457152]])

In [24]:
s = "Hello World"
np.fromiter(s, dtype='<U1')  # Creates an array from the string, each character is an element

array(['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd'], dtype='<U1')

In [ ]:
# Mathematical and Statistical functions
'''
1. np.max --> returns the maximum value in an array
2. np.min --> returns the minimum value in an array
3. np.sum --> returns the sum of all elements in an array
4. np.mean --> returns the mean (average) of all elements in an array
5. np.median --> returns the median of all elements in an array
6. np.std --> returns the standard deviation of all elements in an array
7. np.dot --> returns the dot product of two arrays
8. np.cross --> returns the cross product of two arrays
9. np.argmin --> returns the index of the minimum value in an array
10. np.argmax --> returns the index of the maximum value in an array
11. np.exp --> returns the exponential of all elements in an array
12. np.sqrt --> returns the square root of all elements in an array
13. np.var --> returns the variance of all elements in an array
14. np.log --> returns the natural logarithm of all elements in an array
''' 

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [31]:
np.max(arr)  # Maximum value in the array

np.int64(12)

In [32]:
np.min(arr)  # Minimum value in the array

np.int64(1)

In [33]:
np.sum(arr)  # Sum of all elements in the array

np.int64(78)

In [34]:
np.mean(arr)  # Mean of the array

np.float64(6.5)

In [35]:
np.median(arr)  # Median of the array

np.float64(6.5)

In [36]:
np.std(arr)  # Standard deviation of the array

np.float64(3.452052529534663)

In [37]:
np.var(arr)  # Variance of the array

np.float64(11.916666666666666)

In [38]:
arr2 = np.array([8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
np.dot(arr, arr2)  # Dot product of two arrays

np.int64(1196)

In [72]:
arr3 = np.random.randint(0, 10, (12, 1))  # Random 12X1 array
arr4 = np.random.randint(0, 10, (1, 12))  # Another random 1X12 array
print(arr3.shape, arr4.shape)  # Print shapes of the arrays
np.cross(arr4, arr3)  # Cross product of two arrays

(12, 1) (1, 12)


ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [43]:
np.argmin(arr)  # Index of the minimum value in the array

np.int64(0)

In [44]:
np.argmax(arr)  # Index of the maximum value in the array

np.int64(11)

In [45]:
np.exp(arr)  # Exponential of all elements in the array

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05])

In [46]:
np.sqrt(arr)  # Square root of all elements in the array

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162])

In [47]:
np.var(arr)  # Variance of the array

np.float64(11.916666666666666)

In [48]:
np.log(arr)  # Natural logarithm of all elements in the array

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665])

In [ ]:
# stackning and splitting
'''
1. np.vstack --> stacks arrays vertically (row-wise) - concatenates arrays along the first axis
2. np.hstack --> stacks arrays horizontally (column-wise) - concatenates arrays along the second axis
3. np.concatenate --> concatenates arrays along a specified axis
4. np.split --> splits an array into multiple sub-arrays
5. reshape --> changes the shape of an array without changing its data
'''

In [49]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[7, 8, 9], [10, 11, 12]])

In [50]:
np.vstack((c, d))  # Stacks arrays vertically

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
np.hstack((c, d))  # Stacks arrays horizontally

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [59]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
arr2

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
np.concatenate((arr, arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19])

In [53]:
np.concatenate((c, d), axis=0)  # Concatenates arrays along the first axis (vertical)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
np.concatenate((c, d), axis=1)  # Concatenates arrays along the second axis (horizontal)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [55]:
np.split(arr, 3)  # Splits the array into 3 sub-arrays

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [56]:
np.reshape(arr, (3, 4))  # Reshapes the array to 3 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
# copy and view
'''
# copy - creates a new array with the same data and keeps the original array unchanged
# view - creates a new array that shares the same data as the original array, changes in the new array will affect the original array
'''
x = arr.copy()  # Creates a copy of the array
y = arr.view()  # Creates a view of the array
 
arr[2] = 0

print(arr)  # Original array  
print(x)  # Original array remains unchanged
print(y)  # View of the array reflects the change in the original array

[ 1  2  0  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  0  4  5  6  7  8  9 10 11 12]


In [ ]:
# indexing and slicing
'''
# Indexing - accessing individual elements of an array
# Slicing - accessing a range of elements in an array
'''

In [67]:
print(arr[5])  # Accessing the element at index 5

6


In [68]:
print(arr[7])

8


In [69]:
print(arr[1:5])  # Slicing the array from index 1 to 5 (exclusive)

[2 0 4 5]


In [70]:
arr7 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr7[1,::])  # Accessing all elements in the second row

[4 5 6]
