## numpy

In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np 

In [3]:
# 1D array
ar = np.array([1, 2, 3, 4, 5])
print(ar)

[1 2 3 4 5]


In [4]:
print(type(ar))

<class 'numpy.ndarray'>


In [5]:
# 2D array
ar2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(ar2)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
# 3D array
ar3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
print(ar3)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [7]:
# N-dimentional array
ar4 = np.array([1, 2, 3, 4, 5], ndmin=5) # ndmin specifies the minimum number of dimensions
print(ar4)

[[[[[1 2 3 4 5]]]]]


In [8]:
# Element wise operations
'''
+ - Add elements to arrays element-wise
- - Subtract elements from arrays element-wise
* - Multiply elements of arrays element-wise
/ - Divide elements of arrays element-wise

Note - number of elements in both arrays should be same for element-wise operations
'''

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a + b)  # Addition
print(a - b)  # Subtraction 
print(a * b)  # Multiplication
print(b / a)  # Division

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]


In [9]:
# array creation methods
'''
1. np.zeros----> creates an array filled with zeros
2. np.ones-----> creates an array filled with ones
3. np.full ----> creates an array filled with a specified value
4. np.eye  ----> creates an identity matrix
5. np.arange --> creates an array with a range of values
6. np.random.rand --> creates an array with random float values
7. np.random.randint --> creates an array with random integer values
8. np.empty --> creates an empty array with a specified shape
9. np.copy --> creates a copy of an array
10. np.fromfunction --> creates an array by executing a function over each coordinate
11. np.fromiter --> creates an array from an iterable object
''' 

'\n1. np.zeros----> creates an array filled with zeros\n2. np.ones-----> creates an array filled with ones\n3. np.full ----> creates an array filled with a specified value\n4. np.eye  ----> creates an identity matrix\n5. np.arange --> creates an array with a range of values\n6. np.random.rand --> creates an array with random float values\n7. np.random.randint --> creates an array with random integer values\n8. np.empty --> creates an empty array with a specified shape\n9. np.copy --> creates a copy of an array\n10. np.fromfunction --> creates an array by executing a function over each coordinate\n11. np.fromiter --> creates an array from an iterable object\n'

In [10]:
np.zeros((2, 3))  # 2 rows and 3 columns filled with zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2, 3))  # 2 rows and 3 columns filled with ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.full((2, 3), 7)  # 2 rows and 3 columns filled with sevens

array([[7, 7, 7],
       [7, 7, 7]])

In [13]:
np.eye(3)  # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.arange(0, 10, 2)  # Array with values from 0 to 10 with a step of 2

array([0, 2, 4, 6, 8])

In [15]:
np.random.rand(2, 3)  # 2 rows and 3 columns filled with random float values

array([[0.87174983, 0.76347287, 0.70637802],
       [0.62777407, 0.49151888, 0.6422102 ]])

In [16]:
np.random.randint(0, 10)


3

In [17]:
np.random.randint(0, 10, (2, 3))  # 2 rows and 3 columns filled with random integers between 0 and 10

array([[2, 5, 8],
       [0, 9, 9]], dtype=int32)

In [18]:
np.empty((2, 3))  # Creates an empty array with shape 2x3

array([[0.87174983, 0.76347287, 0.70637802],
       [0.62777407, 0.49151888, 0.6422102 ]])

In [19]:
s = "Hello World"
np.fromiter(s, dtype='<U1')  # Creates an array from the string, each character is an element

array(['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd'], dtype='<U1')

In [20]:
# Mathematical and Statistical functions
'''
1. np.max --> returns the maximum value in an array
2. np.min --> returns the minimum value in an array
3. np.sum --> returns the sum of all elements in an array
4. np.mean --> returns the mean (average) of all elements in an array
5. np.median --> returns the median of all elements in an array
6. np.std --> returns the standard deviation of all elements in an array
7. np.dot --> returns the dot product of two arrays
8. np.cross --> returns the cross product of two arrays
9. np.argmin --> returns the index of the minimum value in an array
10. np.argmax --> returns the index of the maximum value in an array
11. np.exp --> returns the exponential of all elements in an array
12. np.sqrt --> returns the square root of all elements in an array
13. np.var --> returns the variance of all elements in an array
14. np.log --> returns the natural logarithm of all elements in an array
''' 

'\n1. np.max --> returns the maximum value in an array\n2. np.min --> returns the minimum value in an array\n3. np.sum --> returns the sum of all elements in an array\n4. np.mean --> returns the mean (average) of all elements in an array\n5. np.median --> returns the median of all elements in an array\n6. np.std --> returns the standard deviation of all elements in an array\n7. np.dot --> returns the dot product of two arrays\n8. np.cross --> returns the cross product of two arrays\n9. np.argmin --> returns the index of the minimum value in an array\n10. np.argmax --> returns the index of the maximum value in an array\n11. np.exp --> returns the exponential of all elements in an array\n12. np.sqrt --> returns the square root of all elements in an array\n13. np.var --> returns the variance of all elements in an array\n14. np.log --> returns the natural logarithm of all elements in an array\n'

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [22]:
np.max(arr)  # Maximum value in the array

np.int64(12)

In [23]:
np.min(arr)  # Minimum value in the array

np.int64(1)

In [24]:
np.sum(arr)  # Sum of all elements in the array

np.int64(78)

In [25]:
np.mean(arr)  # Mean of the array

np.float64(6.5)

In [26]:
np.median(arr)  # Median of the array

np.float64(6.5)

In [27]:
np.std(arr)  # Standard deviation of the array

np.float64(3.452052529534663)

In [28]:
np.var(arr)  # Variance of the array

np.float64(11.916666666666666)

In [29]:
arr2 = np.array([8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
np.dot(arr, arr2)  # Dot product of two arrays

np.int64(1196)

In [30]:
arr3 = np.random.randint(0, 10, (12, 1))  # Random 12X1 array
arr4 = np.random.randint(0, 10, (1, 12))  # Another random 1X12 array
print(arr3.shape, arr4.shape)  # Print shapes of the arrays
np.cross(arr4, arr3)  # Cross product of two arrays

(12, 1) (1, 12)


ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [ ]:
np.argmin(arr)  # Index of the minimum value in the array

np.int64(0)

In [ ]:
np.argmax(arr)  # Index of the maximum value in the array

np.int64(11)

In [ ]:
np.exp(arr)  # Exponential of all elements in the array

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05])

In [ ]:
np.sqrt(arr)  # Square root of all elements in the array

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162])

In [ ]:
np.var(arr)  # Variance of the array

np.float64(11.916666666666666)

In [ ]:
np.log(arr)  # Natural logarithm of all elements in the array

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665])

In [ ]:
# stackning and splitting
'''
1. np.vstack --> stacks arrays vertically (row-wise) - concatenates arrays along the first axis
2. np.hstack --> stacks arrays horizontally (column-wise) - concatenates arrays along the second axis
3. np.concatenate --> concatenates arrays along a specified axis
4. np.split --> splits an array into multiple sub-arrays
5. reshape --> changes the shape of an array without changing its data
'''

'\n1. np.vstack --> stacks arrays vertically (row-wise) - concatenates arrays along the first axis\n2. np.hstack --> stacks arrays horizontally (column-wise) - concatenates arrays along the second axis\n3. np.concatenate --> concatenates arrays along a specified axis\n4. np.split --> splits an array into multiple sub-arrays\n5. reshape --> changes the shape of an array without changing its data\n'

In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[7, 8, 9], [10, 11, 12]])

In [ ]:
np.vstack((c, d))  # Stacks arrays vertically

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.hstack((c, d))  # Stacks arrays horizontally

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr2

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.concatenate((arr, arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.concatenate((c, d), axis=0)  # Concatenates arrays along the first axis (vertical)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate((c, d), axis=1)  # Concatenates arrays along the second axis (horizontal)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.split(arr, 3)  # Splits the array into 3 sub-arrays

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [ ]:
np.reshape(arr, (3, 4))  # Reshapes the array to 3 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# copy and view
'''
# copy - creates a new array with the same data and keeps the original array unchanged
# view - creates a new array that shares the same data as the original array, changes in the new array will affect the original array
'''
x = arr.copy()  # Creates a copy of the array
y = arr.view()  # Creates a view of the array
 
arr[2] = 0

print(arr)  # Original array  
print(x)  # Original array remains unchanged
print(y)  # View of the array reflects the change in the original array

[ 1  2  0  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  0  4  5  6  7  8  9 10 11 12]


In [ ]:
# indexing and slicing
'''
# Indexing - accessing individual elements of an array
# Slicing - accessing a range of elements in an array
'''

'\n# Indexing - accessing individual elements of an array\n# Slicing - accessing a range of elements in an array\n'

In [ ]:
print(arr[5])  # Accessing the element at index 5

6


In [ ]:
print(arr[7])

8


In [ ]:
print(arr[1:5])  # Slicing the array from index 1 to 5 (exclusive)

[2 0 4 5]


In [ ]:
arr7 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr7[1,::])  # Accessing all elements in the second row

[4 5 6]


## Homework 

In [ ]:
# Create a 3X3 identity matrix
iden_mat = np.eye(3)  # Creating a 3x3 identity matrix
print(iden_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Create a 5X5 matrix filled with the number 7
fil_mat = np.full((5, 5), 7)  # Creating a 5x5 matrix filled with the number 7
print(fil_mat)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
# Generate a 1D array of 10 random integers between 1 and 100
rand_int = np.random.randint(1, 101, 10)  # Generating 10 random integers between 1 and 100
print(rand_int)

[67 45 26 95 82  7 80 99 30 54]


In [ ]:
# Reshap a 1D array of 12 elements into a 3X4 matrix
arr12 = np.arange(1, 13)  # Creating a 1D array with 12 elements
reshaped_arr = arr12.reshape(3, 4)  # Reshaping the array to 3 rows and 4 columns
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Get the mean, median, and standard deviation of an array
print("Mean:", np.mean(arr12))  # Mean of the array
print("Median:", np.median(arr12))  # Median of the array
print("Standard Deviation:", np.std(arr12))  # Standard deviation of the array

Mean: 6.5
Median: 6.5
Standard Deviation: 3.452052529534663


In [ ]:
# Find all element greater than 5 in an array
# greater_than_5 = arr12[arr12 > 5]  # Finding elements greater than 5
greater_than_5 = arr12.find(arr12 > 5)  # Finding elements greater than 5
print("Elements greater than 5:", greater_than_5)

NameError: name 'arr12' is not defined

In [ ]:
# Create a boolean array that identifies even numbers in a given array 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
bool_var = arr % 2 == 0  # Identifying even numbers
print("Boolean array for even numbers:", bool_var)

Boolean array for even numbers: [False  True False  True False  True False  True False  True]


In [31]:
# Create two arrays and perform element-wise multiplication
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print("Element-wise multiplication:", arr1 * arr2)  # Element-wise multiplication

Element-wise multiplication: [ 5 12 21 32]


In [32]:
# replace all odd numbers in an array with -1
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[arr % 2 != 0] = -1  # Replacing odd numbers with -1
print("Array with odd numbers replaced by -1:", arr)  # Print the modified array

Array with odd numbers replaced by -1: [-1  2 -1  4 -1  6 -1  8 -1 10]


In [34]:
# stack two arrays vertically and horizontally
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.vstack((arr1, arr2)))  # Stacking arrays vertically
print(np.hstack((arr1, arr2)))  # Stacking arrays horizontally 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
